# -*- coding: utf-8 -*-
"""DAY-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TepgPSyoeg2IsJN7fNnzKBIvswLJucMW
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="COVID-19 Chest X-Ray Detection",
    page_icon="🩺",
    layout="centered"
)

# -----------------------------
# Custom CSS
# -----------------------------
st.markdown("""
<style>
.stApp{
    background: linear-gradient(to right,#E3F2FD,#FFFFFF);
}

h1{
    text-align:center;
    color:#1565C0;
}

.prediction{
    font-size:25px;
    font-weight:bold;
    text-align:center;
}
</style>
""", unsafe_allow_html=True)

# -----------------------------
# Load Model
# -----------------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("model.keras")      # Change to model.h5 if needed

model = load_model()

# -----------------------------
# Title
# -----------------------------
st.title("🩺 COVID-19 Detection from Chest X-Ray")

st.write(
"""
Upload a **Chest X-ray image** to detect whether it is:

- 🟢 Normal
- 🔴 COVID-19
"""
)

# -----------------------------
# Upload Image
# -----------------------------
uploaded_file = st.file_uploader(
    "Upload Chest X-Ray",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(image,
             caption="Uploaded X-Ray",
             use_container_width=True)

    # -----------------------------
    # Image Preprocessing
    # -----------------------------
    img = image.resize((299, 299))
    img = np.array(img) / 255.0
    img = np.expand_dims(img, axis=0)

    if st.button("Predict"):

        prediction = model.predict(img)

        score = float(prediction[0][0])

        if score > 0.5:
            st.error("🔴 COVID-19 DETECTED")
            confidence = score * 100
        else:
            st.success("🟢 NORMAL")
            confidence = (1 - score) * 100

        st.write(f"### Confidence : {confidence:.2f}%")

        st.progress(min(confidence / 100, 1.0))

        st.write("Raw Model Output:", score)

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")
st.markdown(
"<center>Developed using TensorFlow & Streamlit</center>",
unsafe_allow_html=True
)
